return table.freeze({
    [1] = { Price = 5000, Cooldown = 2.5 },
    [2] = { Price = 25000, Cooldown = 2.25 },
    [3] = { Price = 125000, Cooldown = 2 },
    [4] = { Price = 750000, Cooldown = 1.75 },
    [5] = { Price = 3000000, Cooldown = 1.5 },
    [6] = { Price = 25000000, Cooldown = 1.25 },
    [7] = { Price = 100000000, Cooldown = 1 },
    [8] = { Price = 250000000, Cooldown = 0.75 },
    [9] = { Price = 1000000000, Cooldown = 0.5 },
})
